{
	affichage={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRAffichage.lua",
		prog="affichage"
	},
	bonus={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRBonus.lua",
		prog="bonus"
	},
	config={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRConfig.lua",
		prog="config"
	},
	depart={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRDepart.lua",
		prog="depart"
	},
	etape={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TREtape.lua",
		prog="etape"
	},
	evenement={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TREvenement.lua",
		prog="evenement"
	},
	startup={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRJeu.lua",
		prog="startup"
	},
	joueur={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRJoueur.lua",
		prog="joueur"
	},
	laser={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRLaser.lua",
		prog="laser"
	},
	map={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRMap.lua",
		prog="map"
	},
	mur={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TRMur.lua",
		prog="mur"
	}
}