{
	choices={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TurtleRally-PlayersRemote(Choices).lua",
		prog="choices"
	},
	clicAPI={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TurtleRally-PlayersRemote(ClicAPI).lua",
		prog="clicAPI"
	},
	windows={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TurtleRally-PlayersRemote(Windows).lua",
		prog="windows"
	},
	startup={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally-impera/TurtleRally-PlayersRemote.lua",
		prog="startup"
	},
	sync={
		plateforme="github",
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="Common/Synchro.lua",
		prog="sync"
	}
}