{
	affichage={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRAffichage.lua",
		prog="affichage"
	},
	bonus={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRBonus.lua",
		prog="bonus"
	},
	config={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRConfig.lua",
		prog="config"
	},
	depart={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRDepart.lua",
		prog="depart"
	},
	etape={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TREtape.lua",
		prog="etape"
	},
	evenement={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TREvenement.lua",
		prog="evenement"
	},
	startup={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRJeu.lua",
		prog="startup"
	},
	joueur={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRJoueur.lua",
		prog="joueur"
	},
	laser={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRLaser.lua",
		prog="laser"
	},
	map={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRMap.lua",
		prog="map"
	},
	mur={
		user="Niuttuc",
		repository="ImperaMiniJeu",
		branch="master",
		file="TurtleRally%201.10/TRMur.lua",
		prog="mur"
	}
}